# Generated by Django 5.1.6 on 2025-03-23 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
        ('paypal', '0002_remove_subscription_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='plan',
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paypal.subscription'),
        ),
    ]
