# Generated by Django 5.1.6 on 2025-03-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
